import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex items-center justify-between px-8 py-4 border-b border-gray-200 dark:border-gray-800 bg-white dark:bg-black">
          <span className="text-xl font-bold tracking-tight text-foreground">CryptoTasks</span>
          <div className="flex gap-6">
            <a href="/freelancers" className="text-foreground hover:underline underline-offset-4 font-medium">Freelancers</a>
            <a href="#" className="text-foreground hover:underline underline-offset-4 font-medium">Agent</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
