import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex items-center justify-between px-8 py-6 bg-[#004899] text-white rounded-b-2xl shadow-lg">
          <span className="text-2xl font-bold tracking-tight">CryptoTasks</span>
          <div className="flex gap-8">
            <a href="/freelancers" className="hover:underline underline-offset-4 font-semibold text-lg">Freelancers</a>
            <a href="/agent" className="hover:underline underline-offset-4 font-semibold text-lg">Agent</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
